version: '3.7'

services:
  web:
    container_name: dlp_system
    restart: always
    build:
      context: ./
      dockerfile: ./Dockerfile
    stdin_open: true
    tty: true
    command: sh -c "sleep 2 && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"

    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
      - ${PWD}/logs:/home/app/web/logs
      - ./:/home/app/web
    env_file:
      - ./.env.local
    depends_on:
      - db
    ports:
      - "8000:8000"

  db:
    container_name: dlp_system_db
    restart: always
    image: postgres:14.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.local.db
    ports:
      - 5432:5432


  redis:
    container_name: dlp_system_redis
    restart: always
    command: sh -c 'exec redis-server'
    image: redis:7.0.2-alpine
    volumes:
      - ../redis_data:/var/lib/redis/data/

  celery_worker:
    container_name: dlp_system_celery_worker
    restart: on-failure
    build:
      context: ./
      dockerfile: Dockerfile
    command: sh -c "celery -A dlp_system worker -l info"
    volumes:
      - ./:/home/app/web
    depends_on:
      - web
      - redis
    env_file:
      - .env.local



volumes:
  postgres_data:
  static_volume:
  media_volume:
