# Generated by Django 4.1.3 on 2023-02-10 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dlp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlackFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='File')),
            ],
        ),
        migrations.CreateModel(
            name='SlackMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Text')),
                ('date', models.DateField(verbose_name='Date')),
                ('time', models.TimeField(verbose_name='Time')),
                ('team_id', models.CharField(max_length=255, verbose_name='Team ID')),
                ('channel_id', models.CharField(max_length=255, verbose_name='Channel ID')),
                ('owner_id', models.CharField(max_length=255, verbose_name='User ID')),
                ('files', models.ManyToManyField(related_name='messages', to='slack_.slackfile', verbose_name='Files')),
                ('re_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='dlp.retemplate', verbose_name='Re Template')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
