# Generated by Django 4.1.3 on 2023-02-11 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack_', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slackfile',
            name='filename',
            field=models.CharField(default='', max_length=255, verbose_name='File Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slackfile',
            name='filetype',
            field=models.CharField(default='', max_length=255, verbose_name='File Type'),
            preserve_default=False,
        ),
    ]
