# Generated by Django 4.1.6 on 2023-02-12 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlp', '0001_initial'),
        ('slack_', '0002_slackfile_filename_slackfile_filetype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slackmessage',
            name='re_template',
        ),
        migrations.AddField(
            model_name='slackmessage',
            name='re_templates',
            field=models.ManyToManyField(related_name='messages', to='dlp.retemplate', verbose_name='Re Templates'),
        ),
    ]
